name: Lint Dockerfile

on:
  workflow_dispatch:
   pull_request: {}
   push:
    branches: ["master", "main"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          
